server:
  port: 8081

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/webhook_platform
    username: webhook
    password: webhook
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: delivery-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.webhooks.delivery.job.DeliveryJob
        spring.json.trusted.packages: com.webhooks.delivery.job

webhook:
  delivery:
    timeout: 5s
    max-attempts: 6

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-}]"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info
