server:
  port: 8081

spring:
  application:
    name: delivery-service
  datasource:
    url: jdbc:postgresql://localhost:5432/webhook_platform
    username: webhook
    password: webhook
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info
