server:
  port: 8083

spring:
  application:
    name: webhook-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/webhook_platform
    username: webhook
    password: webhook
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
  data:
    redis:
      host: localhost
      port: 6379

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-}]"

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info
